---
- hosts: all
  remote_user: root
  tasks:
    - name: stop apache service
      service: name=httpd state=stopped
      notify: reboot sequence
  handlers:
    - name: reboot sequence
      changed_when: "true"
      debug: msg='trigger machine reboot sequence'
      notify:
        - get current time
        - reboot system
        - waiting for server to come back
        - verify a reboot was actually initiated
        - verify httpd to start
    - name: get current time
      command: /bin/date +%s
      register: before_reboot
      sudo: false
    - name: reboot system
      shell: sleep 2 && shutdown -r now "Reboot triggered through Ansible"
      async: 1
      poll: 0
      ignore_errors: true
    - name: waiting for server to come back
      local_action: wait_for host="eap1.coe.hst.sin2.redhat.com"  state=started delay=30 timeout=60
      sudo: false
    - name: verify a reboot was actually initiated
      # machine should have started after it has been rebooted
      shell: (( `date +%s` - `awk -F . '{print $1}' /proc/uptime` > {{ before_reboot.stdout }} ))
    - name: verify httpd to start
      local_action: wait_for port=80 host="eap1.coe.hst.sin2.redhat.com" search_regex=OpenSSH delay=30
      sudo: false
