---
- hosts: all
  remote_user: root
  tasks:
    - name: stop apache service
      service: name=httpd state=stopped
    - name: reboot sequence
      changed_when: "true"
      debug: msg='trigger machine reboot sequence'
    - name: get current time
      command: /bin/date +%s
      register: before_reboot
      sudo: false
    - name: reboot system
      shell: sleep 2 && shutdown -r now "Reboot triggered through Ansible"
      register: output
      async: 1
      poll: 0
      ignore_errors: true
    - name: report server rebooted
      debug: msg='server is rebooted'
    - name: waiting for server to come back
      local_action: wait_for host="eap1.coe.hst.sin2.redhat.com"  state=started delay=30 timeout=60
      sudo: false
    - name: verify a reboot was successful
      # machine should have started after it has been rebooted
      shell: (( `date +%s` - `awk -F . '{print $1}' /proc/uptime` > {{ before_reboot.stdout }} ))
    - name: Ensure httpd starts
      service: name=httpd state=started
